import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"

const CreateSubscriptionForm = () => {
  return (
    <>
       <Sheet>
      <SheetTrigger asChild>
       <Button className="bg-amber-500 hover:bg-amber-600 text-black w-full lg:w-fit">
           <span className="text-sm">Create Subscription</span>
        </Button>
      </SheetTrigger>
      <SheetContent className="bg-primary-600 text-white">
        <SheetHeader className="border-b border-b-primary-500">
          <SheetTitle>Subscriptions</SheetTitle>
          <SheetDescription>
            Manage and analyze the recurring revenue generated by your app through subscription plans.
          </SheetDescription>
        </SheetHeader>
        <div className="grid flex-1 auto-rows-min gap-6 px-4">
          <div className="grid gap-3">
            <Label htmlFor="name">Name</Label>
            <Input id="name" />
          </div>
          <div className="grid gap-3">
            <Label htmlFor="description">Description</Label>
            <Textarea rows={10} className="h-[150px]"></Textarea>
          </div>
          <div className="grid gap-3">
            <Select>
              <SelectTrigger id="billing_cycle" className="w-full">
                  <SelectValue placeholder="Billing Circle" />
              </SelectTrigger>
              <SelectContent>
                  <SelectGroup>
                      <SelectLabel>Sort By</SelectLabel>
                      <SelectItem value="monthly">Monthly</SelectItem>
                      <SelectItem value="yearly">Yearly</SelectItem>
                  </SelectGroup>
              </SelectContent>
          </Select>
          </div>
          <div className="grid gap-3">
            <Label htmlFor="price">Price</Label>
            <Input id="price" />
          </div>
        </div>
        <SheetFooter>
          <SheetClose asChild>
            <Button className="bg-amber-500 text-black hover:bg-amber-600">Cancle Subscription</Button>
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
    </>
  )
}

export default CreateSubscriptionForm